stages:
  - setup
  - test
  - publish

variables:
  NODE_IMAGE: ubu1:5000/node-docker-compose:v18
  DOCKER_TLS_CERTDIR: ""
  NODE_ENV: test
  KAFKA_BROKER: localhost:9092

setup-node:
  stage: setup
  image: $NODE_IMAGE
  script:
    - node -v
    - npm -v
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 30m

test:
  stage: test
  image: $NODE_IMAGE
  services:
    - docker:dind
  dependencies:
    - setup-node
  script:
    - docker compose -f docker-compose-tests.yml -p teststack up -d
    - echo "Waiting for Kafka to start..."
    - |
      for i in {1..30}; do
        docker exec kafka kafka-topics --bootstrap-server localhost:9092 --list && break
        echo "Waiting for Kafka... ($i)"; sleep 2
      done
      if [ "$i" = "30" ]; then
        echo "Kafka did not respond after 30 attempts."
        exit 1
      fi
    - |
      if [ -z "$KAFKA_BROKER" ]; then
        echo "KAFKA_BROKER is not defined."
        exit 1
      fi
      echo "KAFKA_BROKER set to '$KAFKA_BROKER'"
    - npm run lint
    - npm run test:unit
    - npm run test:integration
    - docker compose -f docker-compose-tests.yml down

publish:
  stage: publish
  image: $NODE_IMAGE
  dependencies:
    - setup-node
  script:
    - npm publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
      when: always
    - when: never
  variables:
    NODE_AUTH_TOKEN: $NPM_TOKEN
